-- Seed: famous living people (as of 2026). Surnames should be distinctive
-- enough that the player can reasonably identify the intended person.
insert into public.living_people (surname, canonical_first_name, canonical_full_name, country, profession, era, hint) values
('Musk', 'Elon', 'Elon Musk', 'South Africa/USA', 'Entrepreneur/CEO', '21st century', 'Tesla and SpaceX'),
('Messi', 'Lionel', 'Lionel Messi', 'Argentina', 'Footballer', '21st century', '8-time Ballon d''Or'),
('Ronaldo', 'Cristiano', 'Cristiano Ronaldo', 'Portugal', 'Footballer', '21st century', 'CR7'),
('Beyoncé', 'Beyoncé', 'Beyoncé Knowles-Carter', 'USA', 'Singer/Performer', '21st century', 'Former Destiny''s Child'),
('Swift', 'Taylor', 'Taylor Swift', 'USA', 'Singer-songwriter', '21st century', 'Eras Tour'),
('Obama', 'Barack', 'Barack Obama', 'USA', 'Politician', '21st century', '44th US President'),
('Zuckerberg', 'Mark', 'Mark Zuckerberg', 'USA', 'Entrepreneur/CEO', '21st century', 'Meta/Facebook founder'),
('Bezos', 'Jeff', 'Jeff Bezos', 'USA', 'Entrepreneur', '20th-21st century', 'Amazon founder'),
('Gates', 'Bill', 'Bill Gates', 'USA', 'Entrepreneur/Philanthropist', '20th-21st century', 'Microsoft co-founder'),
('Nadella', 'Satya', 'Satya Nadella', 'India/USA', 'CEO', '21st century', 'Microsoft CEO'),
('Pichai', 'Sundar', 'Sundar Pichai', 'India/USA', 'CEO', '21st century', 'Google/Alphabet CEO'),
('Altman', 'Sam', 'Sam Altman', 'USA', 'Entrepreneur/CEO', '21st century', 'OpenAI CEO'),
('Hassabis', 'Demis', 'Demis Hassabis', 'England', 'AI researcher', '21st century', 'DeepMind co-founder'),
('Nolan', 'Christopher', 'Christopher Nolan', 'England/USA', 'Film Director', '21st century', 'Inception and Oppenheimer'),
('Spielberg', 'Steven', 'Steven Spielberg', 'USA', 'Film Director', '20th-21st century', 'E.T. and Jurassic Park'),
('Tarantino', 'Quentin', 'Quentin Tarantino', 'USA', 'Film Director', '20th-21st century', 'Pulp Fiction'),
('Scorsese', 'Martin', 'Martin Scorsese', 'USA', 'Film Director', '20th-21st century', 'Goodfellas'),
('Streep', 'Meryl', 'Meryl Streep', 'USA', 'Actress', '20th-21st century', 'Most Oscar-nominated actor'),
('DiCaprio', 'Leonardo', 'Leonardo DiCaprio', 'USA', 'Actor', '20th-21st century', 'Titanic and The Revenant'),
('Hanks', 'Tom', 'Tom Hanks', 'USA', 'Actor', '20th-21st century', 'Forrest Gump'),
('Washington', 'Denzel', 'Denzel Washington', 'USA', 'Actor', '20th-21st century', 'Training Day Oscar'),
('Lawrence', 'Jennifer', 'Jennifer Lawrence', 'USA', 'Actress', '21st century', 'Hunger Games and Silver Linings Playbook'),
('Portman', 'Natalie', 'Natalie Portman', 'Israel/USA', 'Actress', '20th-21st century', 'Black Swan Oscar'),
('Rihanna', 'Robyn', 'Robyn Rihanna Fenty', 'Barbados', 'Singer/Entrepreneur', '21st century', 'Fenty Beauty founder'),
('Drake', 'Aubrey', 'Aubrey Drake Graham', 'Canada', 'Rapper/Singer', '21st century', 'OVO founder'),
('Eilish', 'Billie', 'Billie Eilish', 'USA', 'Singer-songwriter', '21st century', 'Bad Guy'),
('Bieber', 'Justin', 'Justin Bieber', 'Canada', 'Singer', '21st century', 'Discovered on YouTube'),
('Adele', 'Adele', 'Adele Adkins', 'England', 'Singer-songwriter', '21st century', 'Rolling in the Deep'),
('Sheeran', 'Ed', 'Ed Sheeran', 'England', 'Singer-songwriter', '21st century', 'Shape of You'),
('Kardashian', 'Kim', 'Kim Kardashian', 'USA', 'Media personality/Entrepreneur', '21st century', 'SKIMS founder'),
('Jenner', 'Kylie', 'Kylie Jenner', 'USA', 'Media personality/Entrepreneur', '21st century', 'Kylie Cosmetics'),
('Oprah', 'Oprah', 'Oprah Winfrey', 'USA', 'Media mogul', '20th-21st century', 'Longest-running talk show host'),
('Biden', 'Joe', 'Joe Biden', 'USA', 'Politician', '20th-21st century', '46th US President'),
('Trump', 'Donald', 'Donald Trump', 'USA', 'Politician/Businessman', '20th-21st century', '45th and 47th US President'),
('Harris', 'Kamala', 'Kamala Harris', 'USA', 'Politician', '21st century', '49th US Vice President'),
('Macron', 'Emmanuel', 'Emmanuel Macron', 'France', 'Politician', '21st century', 'President of France'),
('Putin', 'Vladimir', 'Vladimir Putin', 'Russia', 'Politician', '20th-21st century', 'President of Russia'),
('Zelensky', 'Volodymyr', 'Volodymyr Zelensky', 'Ukraine', 'Politician', '21st century', 'President of Ukraine'),
('Modi', 'Narendra', 'Narendra Modi', 'India', 'Politician', '20th-21st century', 'Prime Minister of India'),
('Xi', 'Xi', 'Xi Jinping', 'China', 'Politician', '20th-21st century', 'President of China'),
('Francis', 'Jorge', 'Pope Francis', 'Argentina/Vatican', 'Religious leader', '20th-21st century', 'First Jesuit pope'),
('Thunberg', 'Greta', 'Greta Thunberg', 'Sweden', 'Climate activist', '21st century', 'Fridays for Future'),
('Malala', 'Malala', 'Malala Yousafzai', 'Pakistan', 'Activist', '21st century', 'Youngest Nobel laureate'),
('LeBron', 'LeBron', 'LeBron James', 'USA', 'Basketball player', '21st century', 'Lakers and all-time scoring leader'),
('Curry', 'Stephen', 'Stephen Curry', 'USA', 'Basketball player', '21st century', 'Warriors 3-point king'),
('Federer', 'Roger', 'Roger Federer', 'Switzerland', 'Tennis player', '21st century', '20 Grand Slam titles'),
('Nadal', 'Rafael', 'Rafael Nadal', 'Spain', 'Tennis player', '21st century', 'King of Clay'),
('Djokovic', 'Novak', 'Novak Djokovic', 'Serbia', 'Tennis player', '21st century', 'Most Grand Slam titles'),
('Williams', 'Serena', 'Serena Williams', 'USA', 'Tennis player', '20th-21st century', '23 Grand Slam titles'),
('Biles', 'Simone', 'Simone Biles', 'USA', 'Gymnast', '21st century', 'Most decorated gymnast'),
('Phelps', 'Michael', 'Michael Phelps', 'USA', 'Swimmer', '21st century', '23 Olympic golds'),
('Hamilton', 'Lewis', 'Lewis Hamilton', 'England', 'F1 driver', '21st century', '7-time F1 world champion'),
('Rowling', 'J.K.', 'J.K. Rowling', 'England', 'Author', '20th-21st century', 'Harry Potter series'),
('Murakami', 'Haruki', 'Haruki Murakami', 'Japan', 'Author', '20th-21st century', 'Norwegian Wood'),
('Atwood', 'Margaret', 'Margaret Atwood', 'Canada', 'Author', '20th-21st century', 'The Handmaid''s Tale'),
('Attenborough', 'David', 'David Attenborough', 'England', 'Broadcaster/Naturalist', '20th-21st century', 'Planet Earth narrator'),
('Goodall', 'Jane', 'Jane Goodall', 'England', 'Primatologist', '20th-21st century', 'Chimpanzee research'),
('Dalai', 'Tenzin', 'Tenzin Gyatso', 'Tibet', 'Religious leader', '20th-21st century', '14th Dalai Lama'),
('Banksy', 'Banksy', 'Banksy', 'England', 'Street artist', '21st century', 'Anonymous graffiti artist')
on conflict (surname) do nothing;
