insert into public.surnames (surname, canonical_first_name, canonical_full_name, country, profession, era, hint) values
('Einstein', 'Albert', 'Albert Einstein', 'Germany/USA', 'Physicist', '20th century', 'E=mc²'),
('Mozart', 'Wolfgang', 'Wolfgang Amadeus Mozart', 'Austria', 'Composer', '18th century', 'Child prodigy composer'),
('Curie', 'Marie', 'Marie Curie', 'Poland/France', 'Physicist/Chemist', '19th-20th century', 'Radioactivity pioneer'),
('Shakespeare', 'William', 'William Shakespeare', 'England', 'Playwright', '16th-17th century', 'The Bard'),
('Tesla', 'Nikola', 'Nikola Tesla', 'Serbia/USA', 'Inventor/Engineer', '19th-20th century', 'AC electricity'),
('Darwin', 'Charles', 'Charles Darwin', 'England', 'Naturalist', '19th century', 'Theory of evolution'),
('Mandela', 'Nelson', 'Nelson Mandela', 'South Africa', 'Political leader', '20th century', 'Anti-apartheid'),
('Beethoven', 'Ludwig', 'Ludwig van Beethoven', 'Germany', 'Composer', '18th-19th century', 'Composed while deaf'),
('Galilei', 'Galileo', 'Galileo Galilei', 'Italy', 'Astronomer/Physicist', '16th-17th century', 'Father of modern science'),
('Picasso', 'Pablo', 'Pablo Picasso', 'Spain', 'Painter', '20th century', 'Cubism pioneer'),
('Nightingale', 'Florence', 'Florence Nightingale', 'England', 'Nurse', '19th century', 'Founder of modern nursing'),
('Hawking', 'Stephen', 'Stephen Hawking', 'England', 'Physicist', '20th-21st century', 'Black hole theory'),
('Kahlo', 'Frida', 'Frida Kahlo', 'Mexico', 'Painter', '20th century', 'Self-portraits with Mexican folk art'),
('Napoleon', 'Napoleon', 'Napoleon Bonaparte', 'France', 'Military leader/Emperor', '18th-19th century', 'French Emperor'),
('DaVinci', 'Leonardo', 'Leonardo da Vinci', 'Italy', 'Polymath', '15th-16th century', 'Mona Lisa painter'),
('Chaplin', 'Charlie', 'Charlie Chaplin', 'England/USA', 'Actor/Filmmaker', '20th century', 'The Tramp'),
('Hemingway', 'Ernest', 'Ernest Hemingway', 'USA', 'Author', '20th century', 'The Old Man and the Sea'),
('Turing', 'Alan', 'Alan Turing', 'England', 'Mathematician/Computer Scientist', '20th century', 'Codebreaker and computing pioneer'),
('Tolkien', 'J.R.R.', 'J.R.R. Tolkien', 'England', 'Author/Philologist', '20th century', 'Lord of the Rings'),
('Earhart', 'Amelia', 'Amelia Earhart', 'USA', 'Aviator', '20th century', 'First woman to fly solo across Atlantic'),
('Confucius', 'Confucius', 'Confucius', 'China', 'Philosopher', '5th-6th century BC', 'Confucianism founder'),
('Michelangelo', 'Michelangelo', 'Michelangelo di Lodovico', 'Italy', 'Sculptor/Painter', '15th-16th century', 'Sistine Chapel ceiling'),
('Tchaikovsky', 'Pyotr', 'Pyotr Ilyich Tchaikovsky', 'Russia', 'Composer', '19th century', 'Swan Lake and The Nutcracker'),
('Rembrandt', 'Rembrandt', 'Rembrandt van Rijn', 'Netherlands', 'Painter', '17th century', 'The Night Watch'),
('Gutenberg', 'Johannes', 'Johannes Gutenberg', 'Germany', 'Inventor', '15th century', 'Printing press'),
('Copernicus', 'Nicolaus', 'Nicolaus Copernicus', 'Poland', 'Astronomer', '15th-16th century', 'Heliocentric model'),
('Magellan', 'Ferdinand', 'Ferdinand Magellan', 'Portugal', 'Explorer', '15th-16th century', 'First circumnavigation'),
('Pasteur', 'Louis', 'Louis Pasteur', 'France', 'Chemist/Microbiologist', '19th century', 'Pasteurization and vaccines'),
('Dostoevsky', 'Fyodor', 'Fyodor Dostoevsky', 'Russia', 'Author', '19th century', 'Crime and Punishment'),
('Hitchcock', 'Alfred', 'Alfred Hitchcock', 'England/USA', 'Film Director', '20th century', 'Master of Suspense'),
('Warhol', 'Andy', 'Andy Warhol', 'USA', 'Artist', '20th century', 'Pop Art pioneer'),
('Archimedes', 'Archimedes', 'Archimedes', 'Greece (Syracuse)', 'Mathematician/Inventor', '3rd century BC', 'Eureka!'),
('Bolivar', 'Simón', 'Simón Bolívar', 'Venezuela', 'Military/Political leader', '19th century', 'Liberator of South America'),
('Austen', 'Jane', 'Jane Austen', 'England', 'Author', '18th-19th century', 'Pride and Prejudice'),
('Orwell', 'George', 'George Orwell', 'England', 'Author', '20th century', '1984 and Animal Farm'),
('Vermeer', 'Johannes', 'Johannes Vermeer', 'Netherlands', 'Painter', '17th century', 'Girl with a Pearl Earring'),
('Fibonacci', 'Leonardo', 'Leonardo Fibonacci', 'Italy', 'Mathematician', '12th-13th century', 'Fibonacci sequence'),
('Machiavelli', 'Niccolò', 'Niccolò Machiavelli', 'Italy', 'Political philosopher', '15th-16th century', 'The Prince'),
('Chopin', 'Frédéric', 'Frédéric Chopin', 'Poland/France', 'Composer/Pianist', '19th century', 'Piano poetry'),
('Cervantes', 'Miguel', 'Miguel de Cervantes', 'Spain', 'Author', '16th-17th century', 'Don Quixote'),
('Faraday', 'Michael', 'Michael Faraday', 'England', 'Physicist/Chemist', '19th century', 'Electromagnetic induction'),
('Shackleton', 'Ernest', 'Ernest Shackleton', 'Ireland/England', 'Explorer', '19th-20th century', 'Antarctic expedition'),
('Tubman', 'Harriet', 'Harriet Tubman', 'USA', 'Abolitionist', '19th century', 'Underground Railroad conductor'),
('Brunel', 'Isambard', 'Isambard Kingdom Brunel', 'England', 'Engineer', '19th century', 'Great Western Railway'),
('Gagarin', 'Yuri', 'Yuri Gagarin', 'Russia/USSR', 'Cosmonaut', '20th century', 'First human in space'),
('Goethe', 'Johann', 'Johann Wolfgang von Goethe', 'Germany', 'Writer/Polymath', '18th-19th century', 'Faust'),
('Pankhurst', 'Emmeline', 'Emmeline Pankhurst', 'England', 'Suffragette', '19th-20th century', 'Votes for women'),
('Borges', 'Jorge Luis', 'Jorge Luis Borges', 'Argentina', 'Author', '20th century', 'Labyrinthine fiction'),
('Atatürk', 'Mustafa Kemal', 'Mustafa Kemal Atatürk', 'Turkey', 'Political leader', '20th century', 'Founder of modern Turkey'),
('Sagan', 'Carl', 'Carl Sagan', 'USA', 'Astronomer/Author', '20th century', 'Cosmos series'),
('Kandinsky', 'Wassily', 'Wassily Kandinsky', 'Russia/Germany', 'Painter', '19th-20th century', 'Abstract art pioneer'),
('Feynman', 'Richard', 'Richard Feynman', 'USA', 'Physicist', '20th century', 'Quantum electrodynamics'),
('Solzhenitsyn', 'Aleksandr', 'Aleksandr Solzhenitsyn', 'Russia/USSR', 'Author', '20th century', 'The Gulag Archipelago'),
('Hokusai', 'Katsushika', 'Katsushika Hokusai', 'Japan', 'Artist', '18th-19th century', 'The Great Wave'),
('Planck', 'Max', 'Max Planck', 'Germany', 'Physicist', '19th-20th century', 'Quantum theory founder'),
('Brontë', 'Charlotte', 'Charlotte Brontë', 'England', 'Author', '19th century', 'Jane Eyre'),
('Mendeleev', 'Dmitri', 'Dmitri Mendeleev', 'Russia', 'Chemist', '19th century', 'Periodic table'),
('Coltrane', 'John', 'John Coltrane', 'USA', 'Musician', '20th century', 'A Love Supreme'),
('Wollstonecraft', 'Mary', 'Mary Wollstonecraft', 'England', 'Writer/Philosopher', '18th century', 'Vindication of the Rights of Woman'),
('Vivaldi', 'Antonio', 'Antonio Vivaldi', 'Italy', 'Composer', '17th-18th century', 'The Four Seasons'),
('Houdini', 'Harry', 'Harry Houdini', 'Hungary/USA', 'Magician/Escape artist', '19th-20th century', 'Greatest escape artist'),
('Babbage', 'Charles', 'Charles Babbage', 'England', 'Mathematician/Inventor', '19th century', 'Father of the computer'),
('Lovelace', 'Ada', 'Ada Lovelace', 'England', 'Mathematician', '19th century', 'First computer programmer'),
('Caravaggio', 'Michelangelo', 'Michelangelo Merisi da Caravaggio', 'Italy', 'Painter', '16th-17th century', 'Baroque master of light'),
('Woolf', 'Virginia', 'Virginia Woolf', 'England', 'Author', '20th century', 'Mrs Dalloway'),
('Pavlov', 'Ivan', 'Ivan Pavlov', 'Russia', 'Physiologist', '19th-20th century', 'Classical conditioning'),
('Hertz', 'Heinrich', 'Heinrich Hertz', 'Germany', 'Physicist', '19th century', 'Proved electromagnetic waves'),
('Neruda', 'Pablo', 'Pablo Neruda', 'Chile', 'Poet', '20th century', 'Nobel Prize poet'),
('Nefertiti', 'Nefertiti', 'Nefertiti', 'Egypt', 'Queen', '14th century BC', 'Iconic bust'),
('Gaudi', 'Antoni', 'Antoni Gaudí', 'Spain', 'Architect', '19th-20th century', 'Sagrada Família'),
('Cuvier', 'Georges', 'Georges Cuvier', 'France', 'Naturalist', '18th-19th century', 'Father of paleontology'),
('Nureyev', 'Rudolf', 'Rudolf Nureyev', 'Russia/USSR', 'Ballet dancer', '20th century', 'Greatest male ballet dancer'),
('Rasputin', 'Grigori', 'Grigori Rasputin', 'Russia', 'Mystic', '19th-20th century', 'Influence over Russian royals'),
('Trotsky', 'Leon', 'Leon Trotsky', 'Russia/USSR', 'Revolutionary', '20th century', 'Russian Revolution leader'),
('Plato', 'Plato', 'Plato', 'Greece', 'Philosopher', '4th-5th century BC', 'The Republic'),
('Aristotle', 'Aristotle', 'Aristotle', 'Greece', 'Philosopher', '4th century BC', 'Student of Plato'),
('Cleopatra', 'Cleopatra', 'Cleopatra VII', 'Egypt', 'Pharaoh', '1st century BC', 'Last pharaoh of Egypt'),
('Genghis', 'Genghis', 'Genghis Khan', 'Mongolia', 'Conqueror/Emperor', '12th-13th century', 'Mongol Empire founder'),
('Hypatia', 'Hypatia', 'Hypatia of Alexandria', 'Egypt (Roman)', 'Mathematician/Philosopher', '4th-5th century', 'First notable female mathematician');
